### ISSUE TITLE
English phrases mixed in the German version

### ISSUE THREAD

**Issue by cqx931** [shadoof/thelisteners#20]
> Und für dich zu sprechen, diese Dinge, die du wissen wolltest, sollen, in normalisierter Form, die am öftesten ausgesprochenen menschlichen Wünsche repräsentieren, **such that advertisement may be intimately associated**, so dass Werbung eng verbunden sein kann mit all Ihren geernteten Phrasen, idealerweise, im Moment der Ernte selbst, mit deinen hörenden Gedanken, gegenwärtig mit uns, auch um nicht nur ein gewünschtes Fragment deiner Rede, zu lesen sondern auch ein damit eng verknüpftes. und umgehend brauchbares neues Verlangen. 

https://github.com/shadoof/thelisteners/blob/master/src/main/java/listeners/l10n/Fragments_de_DE.java#L219

**Comment by shadoof** [comment]
Thanks Sally.
