### ISSUE TITLE
ListResourceBundle handling for the supply of built-on-the-fly localized (l10n) Strings

### ISSUE THREAD

**Issue by shadoof** [shadoof/thelisteners#4]
If you're still curious ;) there is a little thing with possible little job that you might look at. For _The Listeners_, per session, I build 10 `fragments` of text into a `LangConstants` singleton. Now that I'm using 'grown-up' localization, I assemble these fragments from a `ListResourceBundle` extension, specifically `listeners.110n.Fragments.java`. You might check out how its done and see if you can figure out a way of actually fetching/building the strings that is more elegant than using the standard (and could-be-'overridden') `public Object[][] contents = ...` declaration in that class.

Also if you look at and run TestHandler in eclipse you'll see how I set up and use some RiMarkov objects, and you may have thoughts about this.

**Comment by shadoof** [comment]
Oh, btw, these aren't bugs. Everything works as I currently want it to.

**Comment by dhowe** [comment]
if it works, it works ;) 
It could certainly be optimised, but I'd only do this if it was either slow, or difficult to understand or extend. Each time you get those 'contents', you create the strings from scratch again, though maybe you only need to do this once (also, each time you use the + or += operator, you create a new String)

The usual way people import other libraries (e.g., RiTa) is by adding it to their pom.xml (but maybe you want the src there for other reasons)

interestingly, a lot of what you are doing in Fragments and its the supporting methods is very RiScript like... (unfortunately not quite ready for java yet)

**Comment by shadoof** [comment]
haven't used RiScript. Is that in rita.js?

**Comment by dhowe** [comment]
Yes, but in v2.0, but will soon be in java as well. You can see the docs here: https://www.npmjs.com/package/rita/v/2.0.0-beta.29

**Comment by shadoof** [comment]
Lovely! I will very likely refactor to use it when it makes it into Java. (I now see, btw, why it can be much better+faster to code in Java than Javascript. All that structure and control, esp. with a reasonable IDE. I would probably already have gone crazy if I was trying to reengineer The Listeners 2.x kludge-fest in Javascript.)
